# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - Revolute 1
      - Revolute 2
      - Revolute 3
      - Revolute 4
    command_interfaces:
      []
    state_interfaces:
      []
hand_controller:
  ros__parameters:
    joint: Revolute 4